[package]
name = "flight_simulator"
version = "0.1.0"
authors = ["Shakya Majumdar <shakyathegreat.majumdar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3"